version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing source dependencies...
      - npm install --global yarn
      - yarn
  build:
    commands:
      - echo Building...
      - NODE_OPTIONS="--max-old-space-size=8192"
      - yarn build ${PROJECT_NAME} --configuration=${APP_ENV} ${BUILD_ARGS}
  post_build:
    commands:
      - cp -av apps/${PROJECT_NAME}/server dist/apps/${PROJECT_NAME}
      - cp -av apps/${PROJECT_NAME}/styles dist/apps/${PROJECT_NAME}
      - cp -av apps/${PROJECT_NAME}/config dist/apps/${PROJECT_NAME}
      - cp -av Procfile dist/apps/${PROJECT_NAME}
      - echo Build completed on `date`
cache:
  paths:
    - 'node_modules/**/*' # Cache `node_modules` for faster `yarn` or `npm i`
    # - '.next/cache/**/*' # Cache Next.js for faster application rebuilds
artifacts:
  files:
    - '**/*'
  base-directory: 'dist/apps/${PROJECT_NAME}'
