# https://medium.com/@karlstad/create-a-github-actions-workflow-that-auto-merges-the-master-back-to-dev-branch-8b1ebe7009b3

name: Sync Main => Staging
on:
  schedule: 
    - cron: "15 12 * * *"
  workflow_dispatch:

jobs:
  sync-main-staging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git fetch --unshallow
    - name: main --> staging
      run: |
          git checkout staging
          git pull
          git merge --no-ff origin/main -m "Auto-merge from main"
          git push